license_test.go
licenses.go

This is how vendoring is supposed to work, so we should follow the
same pattern.

Make sure vendor/ path is checked before GOPATH.

---

.travis.yml
check_signed_off.sh

TRAVIS_COMMIT_RANGE seems to have many people complaining about it
online, and we've had cases where it fails to check pull requests
properly. Use TRAVIS_BRANCH and Git FETCH_HEAD instead, which should
be more stable. See the discussion here:
https://github.com/travis-ci/travis-ci/issues/1719

Switch from unreliable to more stable Travis variable.

---

check_signed_off.sh
license_test.go

```
commit 8741aaa9c32e2110a9bf084f16c2b6693dd1f105
Author: Kristian Amlie <kristian.amlie@mender.io>
Date:   Tue Sep 27 13:40:45 2016
Do license checks between main Travis branch and current HEAD.
On master this is likely to give a zero range, but this is ok, since
testing a range for signoff is useless on master (what would you do
about it?). However, for pull requests it will be the range of new
commits being introduced, which is what we want.
commit 93c4fc7f55e56c306baea8bdd0803104c4c16da3
Author: Kristian Amlie <kristian.amlie@mender.io>
Date:   Tue Sep 27 13:40:26 2016
Test actual licenses, not just mock licenses.
commit 289616786a93f7125d8f58f6ecaa3760625adf24
Author: …
```

Do license checks between main Travis branch and current HEAD.

---

check_license.sh
license_test.go
licenses.go

Call it in cases where the license is inside a file without a standard
license file name.

Add SetLicenseFileForDependency().

---

.travis.yml
check_signed_off.sh

Referring to origin/* is wrong, because that doesn't work for tags.
In fact, there is no way we can refer to tags other than a bare
string, and since we need to use branches and tags interchangably, we
have to make branches follow the same pattern.
Therefore, we have to do the Git magic in this patch to fetch the
branches into local branches with bare names.

Refix Travis references to branches and tags.

---

check_commits.sh

This is necessary when specifying branches of the form:
git rev-list HEAD --not origin/master

Make it possible for check_commits.sh to take more than one argument.

---

check_commits.sh

Ignore git-subtree commits in signoff and changelog checks.

---

check_license_go_code.sh

License test is checking now when the source file was modified and
makes sure the last modification date matches the copyright information
inside the source file.
This way all the modified files need to have the license updated, but
the ones which are not modified can stay with the previous copyright
information.
Signed-off-by: Marcin Pasinski <marcin.pasinski@northern.tech>

Update license check to check for specific copyright year.

---

check_license_go_code.sh

This avoids a couple of pitfalls:
* Doesn't include merges in the candidates for last modified commit
* Tracks renames correctly, not including files as candidates that
have merely been moved, but not changed

Use --follow when checking last modified year of file.

---

.gitignore
.gitlab-ci-check-commits.yml
.gitlab-ci-check-license.yml
.gitlab-ci.yml
README.md

These independent check-commits and check-license pipelines are meant to
be included by any other GitLab Pipeline in the organization.
Note that from Travis to GitLab, the "go build" step has been removed.
This repo does not produce any binary so the build is unnecesary.
Signed-off-by: Lluis Campos <lluis.campos@northern.tech>

Create Pipeline(s) for mendertesting  repo

---

.gitlab-ci-check-commits-changelogs.yml
.gitlab-ci-check-commits-signoffs.yml
check_commits.sh

This is done through adding two flags to the chech_commits.sh script.
One for enabling the signature check, and one for enabling the Changelog check.
In the case that no flags are given, they will both be checked (The old
behaviour).
Also add the ability to pass these parameters to the
'.gitlab-ci-check-commits.yml' file through an environment variable
'MENDERTESTING_ARGS'.

QA-111: Check signed commits on community repositories 

---

.gitlab-ci-check-python3-format.yml
check_python_code_format

This commit adds a '.gitlab-ci-black-format-code.yml' file which can be included
into other projects' .gitlab-ci file, and which, when included, will check that
the Python3 code in the given directories are formatted according to Black's
preferences.
Changelog: Title

QA-131: Add a .gitlab-ci file which can be included in other files

---

check_python_code_format

Quote the strings in the zero-length string test.

Make the check_python_code script not error when no files are wrong

---

.gitlab-ci-check-commits-changelogs.yml
.gitlab-ci-check-commits-signoffs.yml
.gitlab-ci-check-commits.yml
.gitlab-ci-check-python3-format.yml

This is mainly for mender-qa, where there vast majority of times we are
using "master" and wasting precious GitLab CI minutes with commit
checks. It won't hurt saving minutes on other repos neither.
Strictly speaking, we could apply the same principle to all templates,
but let's limit it only to the commit ones: as these are the really
superfluous ones in master while the others could possibly detect
errors in ninja merges.

Skip master execution of mendertesting commit checks

---

.gitlab-ci-check-apidocs.yml
.gitlab-ci-check-golang-dockerimage.yml
.gitlab-ci-check-golang-static.yml
.gitlab-ci-check-golang-unittests.yml

This commit adds the following templates:
* .gitlab-ci-check-golang-static.yml: Static checks like format, gocyclo
* .gitlab-ci-check-golang-unittests.yml: Run unit tests and publish
results into codecov
* .gitlab-ci-check-golang-dockerimage.yml: Build Docker image and
publish it into Docker Hub
* .gitlab-ci-check-apidocs.yml: Check Swagger formatted docs
They cover all common jobs for our Go repos.

Add templates for all common checks in golang repos

---

.gitlab-ci-check-python3-format.yml
check_python_code_format

Previously the formatter checked only the code in the PR. This changes that
functionality to check all the code in the repository, so that no code will ever
be out of sync, regardless of the PR code.

Update the python-format check functionality

---

.gitlab-ci-check-golang-acceptance.yml
.gitlab-ci-check-golang-dockerimage.yml

Set docker:dind image to a fixed version
In the affected templates, so that we can workaround a temporary issue
with latest docker:dind. See MEN-3200
See https://gitlab.com/gitlab-com/support-forum/issues/5194#note_288438588

MEN-3200: Set docker:dind image to a fixed version

---

.gitlab-ci-check-commits-changelogs.yml
.gitlab-ci-check-commits-signoffs.yml
.gitlab-ci-check-commits.yml
.gitlab-ci-check-golang-acceptance.yml
.gitlab-ci-check-license.yml
.gitlab-ci-check-python3-format.yml

It is unnecessary to clone the whole history of the git repository,
a git shallow clone is enough.
Signed-off-by: Fabio Tranchitella <fabio@tranchitella.eu>

Use --depth=1 when cloning git repositories in pipelines

---

.gitlab-ci-check-docker-acceptance.yml
.gitlab-ci-check-docker-build.yml
.gitlab-ci-check-golang-acceptance.yml
.gitlab-ci-check-golang-static.yml
.gitlab-ci-check-golang-unittests.yml

This PR collects a set of changes and extensions for the templates to work with all repositories. It also has as important bugfix!
Best review commit by commit, I think.
Important: two templates have been renamed. Fortunately, only one repo is using them (inventory) so I will coordinate the merges to not affect ongoing PRs.
This PR will then unblock the following PRs:
* https://github.com/mendersoftware/deviceauth/pull/310
* https://github.com/mendersoftware/tenantadm/pull/121
* https://github.com/mendersoftware/inventory/pull/153
* https://github.com/mendersoftware/deployments/pull/393
* https://github.com/mendersoftware/useradm/pull/151

QA-149: Use pipelines templates in all back-end repos

---

.gitlab-ci-check-commits-changelogs.yml
.gitlab-ci-check-commits-signoffs.yml
.gitlab-ci-check-commits.yml
.gitlab-ci-check-golang-unittests.yml

We experienced gitlab pipeline failures due to shallow clones of the git
repository. We set the GIT_DEPTH variable to 0 to explicitly instruct
the GitLab Runners to perform a full clone.
See original commit in deployments-enterprise repo:
https://github.com/mendersoftware/deployments-enterprise/commit/989a6915fc44764ec6ef36df517cb12ea760d7f5

Set GIT_DEPTH variable to templates doing commit checks

---

.gitlab-ci-check-docker-build.yml
.gitlab-ci-check-golang-unittests.yml

A template user can now use this variable to instruct the template to
expect the Dockerfile in a subdirectory rather than in the root.
Renamed the build job to make explicitly say docker and slightly improve
documentation in unit test template.

Support building docker images in any dir via DOCKER_DIR

---

.gitlab-ci-template-k8s-test.yml

Ported from mender-helm repository and expected to be reused in saas
repository and other k8s related CI scripts.
Reviewed already in https://github.com/mendersoftware/mender-helm/pull/10

Add template to run k8s tests via Kubernetes in Docker setup

---

.gitlab-ci-check-docker-build.yml

Any repo with staging branch, will now publish into its own registry
images with tags staging_<git-sha>

MEN-3344: Extend Docker template to publish staging images

---

.gitlab-ci-check-docker-acceptance.yml
.gitlab-ci-check-docker-build.yml

- [templates] Take password from CLI on docker login calls
The --password-stdin option is throwing errors in some GitLab shared
runners. The password will be masked anyway, so it is safe.
- [docker-build-template] Log in in both registries inconditionally
Now all repos have both credentials anyway (inheriged from the group) so
just log in in both.
- [docker-build-template] Publish Enterprise images to Docker Hub
Add an extra job for Enterprise repo (i.e. when the caller has
registry.mender.io in DOCKER_REPOSITORY) to publish the image with the
same tags into Docker Hub.

Templates Docker publish related fixes

---

.gitlab-ci-check-docker-build.yml

- [docker-build-template] Remove internal template
It seems like GitLab support extending any job, so remove the internal
template. The motivation is to have a clearer interface and not
encourage users to extend the internal template to avoid breaking
changes later on.
- [docker-build-template] Support custom Dockerfile filename
Let the user specify a different Dockerfile filename for their build via
optional env variable DOCKERFILE.

Support custom Dockerfile filename

---

.gitlab-ci-check-docker-build.yml

For repos using a different DOCKERDIR, the DOCKERFILE needs to be
adjusted accordingly.
Fixes commit 0745070.

[docker-build-template] Fix DOCKERDIR/DOCKERFILE usage

---

.gitlab-ci-check-docker-build.yml

From 2.4.x on, the rolling release will be following mender-N.M.x, where
N.M is the Mender (product) version instead of the individual repo
version.

[docker-build-template] MEN-4366: Add publish jobs for new versions

---

.gitlab-ci-check-docker-build.yml

So that :mender-master and :mender-master type of tags are also
published into the container registries.

[docker-build-template] Extend new versioning to master images

---

.gitlab-ci-check-docker-build.yml

To avoid conflict in deployments repo where an "integration" directory
already exists.

[docker-build-template] Rename integration clone to mender-integration

---

.gitlab-ci-check-docker-build.yml

For a repo using the template which is not part of any Mender release,
skip the actual tagging/publishing of mender-VERSION kind of tag.
Signed-off-by: Lluis Campos <lluis.campos@northern.tech>

[docker-build-template] Skip publish:image:mender for non release repos

---

.gitlab-ci-check-docker-build.yml

Yet another case where we need to skip the publish is when the repo is
not found at all.

[docker-build-template] Skip publish:image:mender for not found repos

---

licenses.go

The error is already printed as the Error message. Also the err as the message
panics on older versions of testify.

fix: Remove the err message from the NoErr assertion 

---

.gitlab-ci-check-docker-build.yml

So that branch 1.2.x of a given repo gets published as <repo>:1.2.x (and
mender-1.2.x) instead of 1-2-x.
Renamed a bit the env variables to clarify their usage.
Obs! This will not work for publishing branches with slash (like
feature/my-coool-stuff) but that we can fix later on.

[docker-build-template] REF_NAME instead of REF_SLUG for publish tags

---

.gitlab-ci-check-docker-build.yml

- [docker-build-pipeline] Cleanup unnecessary variable
- [docker-build-template] Install missing pip3 in Alpine jobs
For some reason latest Alpine image does not install pip3 when
installing Python 3.
Similar to https://github.com/mendersoftware/mender-qa/pull/401

[docker-build-template] Install missing pip3 in Alpine jobs

---

.gitlab-ci-check-golang-static.yml
.gitlab-ci-check-golang-unittests.yml
.gitlab-ci.yml

unfortunately go packages can't be installed without changing a projects go.mod
if using a gomod enabled go version
deactivating gomod fixes this

golang-tests: prevented go mod tracking of test dependencies

---

check_commits.sh

Not only dependabot does not include Changelog tags, but also the commit
sign does not match the Git user.
This commit partially reverts incomplete fix from ffc2e5e and instead
just skips all checks for these commits.

[check_commits] Skip all checks for dependabot commits

---

check_commits.sh

Without quotes, `if [ -n ]` validates to true. Bug introduced at
ffc2e5e.

[check_commits] Fix typo if conditions

---

.gitlab-ci-check-docker-build.yml

* [docker-build-template] Keep master tags after 2.3 EOL
Adjust the comment, we still would like to keep the :master tags for any
repo that is not part of a Mender release.
* [docker-build-template] QA-184: publish feature Docker images
Publish Docker images for any branch matching feature-* pattern.

QA-184: publish feature Docker images

---

check_commits.sh

* [check_commits] Accept "All" as a valid Changelog keyword
* [check_commits] Restore Changelog check for dependabot

[check_commits] Accept "Changelog: All" and restore check for dependabot

---

.gitlab-ci-check-docker-build.yml

Images :mender-X.X.x for enterprise repositories were not being
published into Docker Hub due to this bug in the template.

[docker-build-template] Fix publish:image:mender:dockerhub

---

.gitlab-ci-check-docker-build.yml

To accommodate for repos that use master/production branches, like
mender-docs-site.

[docker-build-template] Publish image on production branch

---

.gitlab-ci-check-docker-acceptance.yml
.gitlab-ci-check-golang-unittests.yml

It has happened a couple of times that the codecov script fails to
upload the coverage for either acceptance or unit tests, but rerunning
the stage succeeds.
*(This PR is just a suggested temporary solution to the problem)*

Add retries to acceptance/unit tests codecov upload

---

.gitlab-ci-check-docker-build.yml

So that later stages could use them

[docker-build-template] Save Docker image(s) digests in dotenv file

---

.gitlab-ci-check-docker-acceptance.yml
.gitlab-ci-check-golang-unittests.yml

This PR brings coveralls integration without removing codecov, so that the development process does not get affected for now.
For now, only `devicauth` is activated and you can see the it working in [this PR](https://github.com/mendersoftware/deviceauth/pull/397) and in [coveralls](https://coveralls.io/github/mendersoftware/deviceauth).
I need however to merge these changes into master to be able to finish the PoC; mainly because until we don't have reports from master we cannot see how the "diff" feature works.

QA-220: Migrate coverage reporting to coveralls

---

.gitlab-ci-check-docker-acceptance.yml
.gitlab-ci-check-golang-unittests.yml

To prevent reports from "HEAD detached at ..." branches.

[coveralls] Set also CI_BRANCH env variable

---

.gitlab-ci-check-apidocs.yml

The problem with using LATEST/OLDSTABLE is that it was hardcoded in the
mender-api-docs repository, so that for a short while (while the release
is in progress) we would actually be building latest (say, 2.5) while
publishing as oldstable (say, 2.4).
Note that this has not been a problem because as per today we have not
had 2.4/2.3 API docs in production.
A more permanent fix will follow.

[apidocs template] Use BUILD_X_Y instead of LATEST/OLDSTABLE

---

.gitlab-ci-check-apidocs.yml

So that the API site can be rebuild without changes to docs/* files,
which might come in handy during some maintenance tasks.
To support that, the limited only/except logic has been replaced with
the more expressive rules syntax.

[check-apidocs pipepeline] Support manual trigger for API site build

---

.gitlab-ci-check-apidocs.yml

This seems to have been broken for a long time, but working just fine
for master and hosted builds.

[check-apidocs template] Fix typo in if expression

---

.gitlab-ci-check-apidocs.yml

On any content change, we need to trigger both master (staging) and
production pipelines of mender-api-docs, so that both sites get updated.

[check-apidocs template] Trigger production build/publish/sync

---

.gitlab-ci-check-docker-deploy.yml
.gitlab-ci-template-k8s-test.yml

Inspired in current CI/CD from Mender Docs Site(s) repositories, and
meant to be reused across repos in the mendersoftware organization.

New check-docker-deploy template to generalize CI/CD process

---

.gitlab-ci-check-apidocs.yml

The trigger:apidocs:rebuild-mender-api-docs job is now generalized and
does not require customization anymore for Mender specific versions.
The job relies entirely on the release_tool to determine which version
needs rebuilding, and sets the BUILD_X_Y=true variable accordingly when
triggering the rebuild of the API docs repository.

Enhance gitlab-ci-check-apidocs to make it generalized

---

.gitlab-ci-check-docker-acceptance.yml
.gitlab-ci-check-golang-unittests.yml

For these (for example Mender 2.4.x repos), goveralls call fails finding
the source code in GOPATH and GOROOT.
Some minor beautifications along the way.

[golang-unittests] Fix publish job for repos with no Go modules support

---

check_license.sh

Inspired by this package: https://github.com/nats-io/nats.go

'*.go' directories do not need to be covered by a license file.

---

check_license_source_files.sh

Some vendored code might contain .py files for which we don't want to
run our license check.

[check_license_source_files.sh] Skip vendor dir for Python

---

.gitlab-ci-check-docker-build.yml

So that the template can be used on repositories with credentials for a
single registry.

[docker-build template] Do not fail on missing credentials

---

.gitlab-ci-check-docker-acceptance.yml
.gitlab-ci-check-docker-build.yml
.gitlab-ci-check-docker-deploy.yml

* [check-docker-*] Replace only/except with modern rules
The main motivation is to have an easier way to override rules by user
pipelines.
According to GitLab documentation only/except are not going to be
developed further, so better to switch to the new standard.
* [check-docker-build] Deprecate publishing :M.N.x tags
Since Mender 2.3 went EOL, there is no more use for these tags (we now
publish release branches using :mender-M.N.x tags)

 [check-docker-*] Replace only/except with modern rules (+ cleanup)

---

.gitlab-ci-check-docker-acceptance.yml
.gitlab-ci-check-docker-build.yml

When no match, rules default to not adding the job in the pipeline. So
all the jobs that were excluded for saas tags require a final catch all
rule for them to be included in the pipelines.
Amends commit 431bc37f452d155ef555852315ba947f67fac1c5

[check-docker-*] Amend rules

---

.gitlab-ci-check-docker-build.yml
.gitlab-ci-check-docker-deploy.yml

Main motivation is to specify empty needs for docker build, so that this
can start without waiting for previous stages to complete.

[docker-build/deploy] Switch from dependencies to needs

---

.gitlab-ci-check-apidocs.yml

Fix: api-docs-site trigger BUILD_X_Y variables

---

.gitlab-ci-check-docker-acceptance.yml

So far the repos that have been migrated have kept a dummy Dockerfile
just to satisfy the template. Just check for the file here instead.
Extra:
* [docker-acceptance] Collect results as GitLab junit report

[docker-acceptance] Improve support on repos using common tester image

---

.gitlab-ci-check-docker-build.yml
.gitlab-ci-check-docker-deploy.yml

This partially reverts 09f6522e, resulting a mix of "needs" for the
build job and "dependencies" for publish jobs. The motivation is that we
shall not publish containers if there is any job failing in a previous
stage.
Reasoning can be found at:
https://github.com/mendersoftware/gui/pull/1603#issuecomment-843841981
Signed-off-by: Lluis Campos <lluis.campos@northern.tech>

[docker templates] Revert to "dependencies" for publishing jobs

---

check_license.sh

On checksum mismatch shasum returns non-zero and the script exists
silently. Now it will print the warning before clean-up.
For example: "shasum: WARNING: 1 computed checksum did NOT match"

check_license.sh: Print shasum output when mismatches

---

.gitlab-ci-check-docker-acceptance.yml
.gitlab-ci-check-docker-build.yml

If the docker virtual network interface MTU is higher than the physical
outgoing MTU, the interface becomes unresponsive.
https://gitlab.com/gitlab-com/gl-infra/production/-/issues/5590

[CI] Lower maximum transmission unit for docker services

---

mender-ci-common.sh

Implementing save/load from S3 temp bucket.
The idea is to be able to extend this file with any function that might
be shared by two ore more pipelines.

Add mender-ci-common.sh with helper functions for any pipeline

---

mender-ci-common.sh

So that the functions can be sourced by non-bash shells.

mender-ci-common.sh: Use POSIX syntax

---

.gitlab-ci-check-golang-lint.yml
.gitlab-ci-check-golang-static.yml
.golangci.yml

This template is meant to replace .gitlab-ci-check-golang-static.yml,
but changing the linters there will terribly break all release branches
of many repositories.
Adding a new template instead and making a note on not using the old
one.

QA-235: Add new template .gitlab-ci-check-golang-lint.yml

---

.golangci.yml

.golangci.yml: Add missing goimports linter

---

.gitlab-ci-check-python3-format.yml

Latest release 8.1.0 removed _unicodefun expected by the black version
we are using.

check-python3-format: Set click dependency to previous release

---

.gitlab-ci-check-docker-acceptance.yml
licenses.go

- this is to also support extracting files from scratch based images

chore: made binary extraction no longer rely on a shell

---

.gitlab-ci-check-commits.yml
.gitlab-ci.yml
check_commits.sh
commitlint/commitlint
commitlint/grammar.md
commitlint/testcommitlint.sh

This adds a conventional commits checker written in `AWK`, which checks the format of our commits through the regualar `check-commits` script.

QA-363: Enable semantic commits checking

---

commitlint/commitlint
commitlint/testcommitlint.sh

This worked on all other commits, as they had both a Ticket and a Changelog footer.
Without this, the error message spit out was wrong, in that the Changelog was missing.

fix: the commitlint parser had a lookahead bug for no body commits

---

commitlint/grammar.md

docs(commitlint): typo in the grammar specification for refactor

---

check_license_source_files.sh

* in case a licence check on a source file fails, replace tab with 4 spaces and try again
Ticket: QA-441

chore: Licence checker on source files adjustment for 1.19 go fmt

---

.gitlab-ci-check-docker-acceptance.yml

Coveralls.io implemented a new end-point (Rerun Build Webhook) to trigger a rebuild of the coverage report when multiple builds are in use.  Without a call to this end-point, the aggregated coverage report for builds could miss data from one of the builds, leading to an erroneous drop in coverage which can cause a failed check on GitHub.
Ticket: None

feat: call the rerun_build endpoint to finalize the coverage report

---

.gitlab-ci-check-commits-signoffs.yml
.gitlab-ci-check-commits.yml
.gitlab-ci-check-license.yml
.gitlab-ci-check-python3-format.yml
check_commits.sh

Instead of "symmetric difference notation".
The list of commits that we should prevent from leaking are all the
commits from staging/hosted branches that are not in the target branch
(aka range), but we should ignore other commits that are already in the
target branch (aka symmetric difference).
See: https://git-scm.com/docs/git-rev-parse#_dotted_range_notations

fix(check_commits.sh): Use "range notation" for git rev-parse command

---

commitlint/commitlint
commitlint/testcommitlint.sh

```
commit 4410811b89749ab1c1f17f25bbe8ace919baf8e0
Author: Kristian Amlie <kristian.amlie@northern.tech>
Date:   Mon Oct 3 11:42:44 2022
fix(commitlint): Fix bug with multiple multiline changelogs.
The `empty_line` function already advances, so we should not advance
again at the end of the loop, or we end up skipping a token.
Ticket: None
commit 045a2d771301ee4e098ee16233d360caee435e11
Author: Kristian Amlie <kristian.amlie@northern.tech>
Date:   Mon Oct 3 11:41:05 2022
chore(commitlint): Add clearer current/next token debug logging.
It's a bit confusing without it because the "Matched" log entries
refer to the next token, not the current one.
commit …
```

Fix bug with multiple multiline changelogs. 

---

check_license.sh

fix: check licences: exclude certain files.
license checker does not allow certain files to be created.
we explicitly exclude *.[c,go,cpp] from the check.
see:https://github.com/mendersoftware/devicemonitor/pull/167
Ticket: QA-492

fix: check licences: exclude certain files.

---

commitlint/commitlint
commitlint/testcommitlint.sh

There is no reason for them to be case sensitive, and it's confusing for contributors. Also, several old commits already carry tags like these.
Note the added line-beginning anchor in the regex. This was always wrong because it would match "Cancel-changelog" as well, but because the test used a lowercase "c", it wasn't caught until we switched it to be case insensitive.
Ticket: none

fix: Make commit tags case insensitive.

---

.gitlab-ci-check-docker-build.yml

This tarball is passed as pipeline artifacts between build and publish jobs.
For most of the repositories, the filename is just an implementation detail and irrelevant. While setting a unique name enables for advance uses cases where a repository might override the build job, for example.

ci: Use repository name for Docker image tarball save/load

---

.gitlab-ci-check-docker-build.yml

It seems like env variables in `artifacts` do not expand using bash syntax and the default path is evaluating to `/image.tar`.
Duplicate the paths instead, which will issue a warning on missing one of the two paths but that is acceptable.

ci: Fix artifacts default path for build image

---

.clang-format

I don't quite understand why the -4 is necessary. According to the `IndentAccessModifiers` docs [1] it should already do it correctly when it is set to false. The Google style has an
`AccessModifierOffset` default of -1, but this still doesn't explain the behavior.
This fixes a mixed-tabs-and-spaces issue with access modifiers.
[1] https://clang.llvm.org/docs/ClangFormatStyleOptions.html

fix: Put C++ access modifiers on same level as parent class.

---

.clang-format

chore: Tweak clang-format constructor initializers indent setting.

---

.gitlab-ci-check-docker-acceptance.yml
.gitlab-ci-check-docker-build.yml
.gitlab-ci-check-docker-release-indep.yml

Introduced at fa69beb as a temporary workaround and fixed long ago.

chore: Remove obsolete max MTU workaround

---

.gitlab-ci-check-docker-release-indep.yml

It turns out that busybox implementation of sort and tail does not support the long arguments.
Amends commit 630089ee42519237d967093744134cbfbae6ab78

fix: Use short arguments for sort and tail

---

.gitlab-ci-check-commits-signoffs.yml
.gitlab-ci-check-commits.yml
.gitlab-ci-check-golang-unittests.yml
.gitlab-ci-check-license.yml

By explicitly defining `GIT_STRATEGY: clone`.
We have a set of tests that require a full clone of the repository, which was already using `GIT_DEPTH: 0` to disallow shallow clone.
However according to GitLab documentation [1], the job might still do a `fetch` instead of `clone` when it can reuse the workspace from a previous job. So if the previous job of the runner was one with a shallow clone (unit tests, format check) then the new job that requires full clone will fail.
My theory is that we have not seen it before because while using public runners it was very unlikely to happen that we _could_ reuse the workspace. Now, with our private runners, this will happen rather often.
See issue reported in GitLab [2] and the recommended workaround [3].
* [1] …

fix: Avoid reusing (shallow) workspace for git test jobs

---

.gitlab-ci-check-docker-build.yml

Amends commit 02c6ffa5.
For some reason for jobs where this variable is undefined it is now resolving to `.`, which makes the job collect all workspace (the git repo) issuing warnings along the way.
Message from CI follows:
```
Uploading artifacts...
.: found 2882 matching artifact files and directories
image.tar: found 1 matching artifact files and directories
WARNING: Part of .git directory is on the list of files to archive
WARNING: This may introduce unexpected problems
```
This commit somewhat reverts 02c6ffa5 putting the artifact recollection to a one-liner but using a relative path.

ci: Fix artifact recollection in docker build template

---

.gitlab-ci-check-docker-deploy.yml

When reusing the workspace, a remote with name `github` already exists. Move instead to a temporary workspace.
See also related fix 4d17fc8.

QA-550: fix: Make sync:image job work when reusing the workspace

---

.gitlab-ci-check-commits-signoffs.yml
.gitlab-ci-check-commits.yml
.gitlab-ci-check-golang-unittests.yml
.gitlab-ci-check-license.yml
.gitlab-ci-check-python3-format.yml
.gitlab-ci.yml

This is necessary when workers are reused. Since the repository, and its branches, may already be there locally, we have to force update them.

Force branch update so it succeeds even when it pre-exists.

---

.clang-format

By using a format that doesn't require knowing the tab width. This turns this:
```
class Stuff : public A,
public B {
```
into:
```
class Stuff :
public A,
public B {
```

chore(clang-format): Break inheritance lists better.

---

.gitlab-ci-check-apidocs.yml

- this is in order to help use automatic code generation as the api specs in their current form fail due to several errors
- instead of failing right away and blocking development, the job failure is tolerated
Ticket: None

feat: extend api doc validation with a more thorough check

---

.gitlab-ci-check-apidocs.yml

this silences all the `Mapping key must be a string scalar rather than number` for the response definitions, there was a longer discussion [here](https://github.com/OAI/OpenAPI-Specification/issues/2171) which could serve as an argument to enforce strings there, but at this point I think it's better to first focus on other issues we have in the api specs
report example [here](https://gitlab.com/Northern.tech/Mender/inventory/-/pipelines/886844179/test_report)

chore: moved errors on api spec parsing to the warning level

---

.gitlab-ci-check-golang-unittests.yml

in the golang unit tests pipeline temporarily switch from golang:1.20 to golang:1.20.4, because of issues with latest version of golang:1.20

golang unit test fix

---

.gitlab-ci-check-golang-unittests.yml

Allows us to update debian image once mendersoftware/go-lib-micro#201 is merged and pulled to all backend services.

ci(go/units): Add TEST_MONGO_URL to unit tests job template

---

.gitlab-ci-check-docker-build.yml

* Required to Ticket: ALV-27 (Alvaldi-docs)
* Requires the base image build: https://github.com/mendersoftware/mender-test-containers/pull/362
* New `build:docker-multiplatform` build job added, it runs only with `MULTIPLATFORM_BUILD: "true"` 
* Can't OCI images with multi-arch manifests in the Gitlab Artifacts, so I'm using the Gitlab Registry with `--push` by pushing the image with the tag `${CI_PIPELINE_ID}` 
* The publish job is using `regclient` which has multi-arch manifests capabilities.
* With registry caching we can save some time:
```
--cache-to type=registry,ref=${CI_REGISTRY_IMAGE}:ci_cache,mode=max
--cache-from type=registry,ref=${CI_REGISTRY_IMAGE}:ci_cache
```
Also please notice that the source Dockerfile could be cross-compilation compliant, e.g.:
```
FROM …
```

Docker multiplatform build

---

.gitlab-ci-check-golang-unittests-v2.yml

The Debian image comes with gcc and libc pre-installed lowering the setup complexity for repositories requiring CGO.

chore: Change golang image used in unittests from Alpine to Debian

---

.gitlab-ci-check-helm-version-bump.yml

Ticket: ALV-47
Updates the alvaldi (or mender) helm chart files:
it sets the new Image Tag into:
* `values-staging.yaml` for the staging env
* `values-prod.yaml` for the prod env
It bumps a new `Chart.yaml` semver version:
* `x.y.buildid-staging` for the staging env (pre-releases)
* `x.y.buildid` for the prod env (stable releases)

Helm chart version bump

---

.gitlab-ci-check-docker-build.yml

This template is used by many repositories that build and publish Docker images. For Mender specific images, there are extra jobs that deal with Mender specific use cases.
Ideally these jobs should be disabled (removed from the pipeline) but so far we were only early exiting leaving the job "green".
With this change we return an specific error code to fail the job while we allow for the whole pipeline to continue.
The motivation is to better visualize what the job has done (nothing) instead of visualizing it as just success (while doing nothing).

ci: Allow to fail Mender specific jobs on build/publish template

---

.gitlab-ci-check-helm-version-bump.yml

Prevents pre-release builds inception:
`alvaldi-0.5.1-1015489838-staging-1015525000-staging+2`

chore: fix PATCH_VERSION when pre-release is found

---

.gitlab-ci-check-license.yml

fix: fixed missing mendertesting environment in go license checks

---

.gitlab-ci-check-golang-lint.yml
.gitlab-ci-check-golang-static.yml

recently I've come across the vendor check job taking a while to start ([here](https://gitlab.com/Northern.tech/Mender/deployments-enterprise/-/jobs/5212756466)), so this should skip it if no `vendor` folder is present

chore: made vendor check get skipped if no vendor folder available

---

.gitlab-ci-check-license.yml

- the exists requirement turned out not to be AND but OR checking for existence
this should address [this job failure](https://gitlab.com/Northern.tech/Mender/mender/-/jobs/5216358650)

fix: prevented non-yocto go license check from running

---

.gitlab-ci-check-license.yml

- the existence of go.mod still was enough to trigger the job, so since the repos running this newer check are golang so far, default to golang and let other environments base their trigger on more unique files
Ticket: None

fix: prevented non-yocto go license check from running pt2

---

commitlint/commitlint

Useful for example to downgrade the changelog of a `feat` or `fix` commit.

fix: Accept `chore` context for changelogs

---

commitlint/commitlint
commitlint/testcommitlint.sh

A word is not a sequence of arbitrary **printable** characters. It's shouldn't contain dashes either, but in our case it simplifies things. For example, commit scope can then be a word in parantheses.
This fixes issues with commit messages containing scope and parantheses in the title, e.g. when mentioning SomeFunction().

fix(commitlint): Fix the definitions of WORD and COMMIT_SCOPE

---

.gitlab-ci-check-docker-build.yml

To be used later in the QA pipeline
Ticket: QA-647

Publish the last stable build to the CI registry

---

.gitlab-ci-check-helm-version-bump.yml

instead of shared runners
Ticket: None

Helm rollout: using project runner

---

.gitlab-ci-check-docker-acceptance.yml

Three friends:
* https://github.com/mendersoftware/mender-qa/pull/723
* https://github.com/mendersoftware/mendertesting/pull/315
* https://github.com/mendersoftware/mender-test-containers/pull/495
Ticket: QA-505
Signed-off-by: Lluis Campos <lluis.campos@northern.tech>
(cherry picked from commit 2b101b91da74c5434783e103df6e123a0a0deca8)

ci: Run acceptance tests with a candidate base image

---

check_python_code_format

Turns out that this conflicts with loading custom excludes from `pyproject.toml`. Looks like there is no easy way to have both, so revert the generic fix and rely on filters in each repo instead.
This reverts commit 01aa2e3dc1c3d1b909ef319739acffe38e4aea11.

revert: "test: Don't check vendor folders for correct Python formatting."

---

.gitlab-ci-github-status-updates.yml

This is a nice to have optimization. See comment.

ci: Set empty `dependencies` to the status jobs

---

.gitlab-ci-check-commits-signoffs.yml
.gitlab-ci-check-commits.yml
.gitlab-ci-check-license.yml
.gitlab-ci-check-python3-format.yml
.gitlab-ci-check-shell-format.yml
.gitlab-ci-github-status-updates.yml
.gitlab-ci.yml

Using CI_DEPENDENCY_PROXY_DIRECT_GROUP_IMAGE_PREFIX instead of CI_DEPENDENCY_PROXY_GROUP_IMAGE_PREFIX to better manage permissions
Ticket: QA-705

Move env var to direct group download

---

.gitlab-ci-check-docker-acceptance.yml
.gitlab-ci-check-golang-unittests-v2.yml
.gitlab-ci-check-golang-unittests.yml
.gitlab-ci-github-status-updates.yml
mender-ci-common.sh

The container image `appropriate/curl` has not been updated for 6 years.
See:
* https://github.com/mendersoftware/mender-qa/commit/1b080adb31432251eb0e9abc6374f8696a02edd3

ci: Replace base image for `curl` only jobs

---

.golangci.yml

my local linter executions were failing due to the following:
```
[error] level=warning msg="The linter 'structcheck' is deprecated (since v1.49.0) due to: The owner seems to have abandoned the linter. Replaced by unused."
level=warning msg="The linter 'varcheck' is deprecated (since v1.49.0) due to: The owner seems to have abandoned the linter. Replaced by unused."
level=warning msg="The linter 'deadcode' is deprecated (since v1.49.0) due to: The owner seems to have abandoned the linter. Replaced by unused."
level=error msg="[linters_context] deadcode: This linter is fully inactivated: it will not produce any reports."
level=error msg="[linters_context] structcheck: This linter is fully inactivated: it will not produce any reports."
level=error msg="[linters_context] varcheck: This …
```

chore: removed deprecated linters

---

.gitlab-ci-check-docker-build.yml

By default blank, but opening the door for individual repos to inject extra arguments, for example extra `--build-arg ...` flags.

Pass user specified arguments to docker build command

---

.gitlab-ci-check-docker-build.yml

Ticket: QA-752
Recently, a docker login failure is waiting for 15 min to wait for web browser login. This slows down a lot the pipelines that don't need login to docker, but they are reusing the mendertesting shared pipeline configurations.
With this change, we'll ignore the docker login if the variable is not set.

Avoid docker login hangs when missing creds  

---

utils/cliff.toml

By exposing the cliff.toml file in the mendertesting repository, other projects and gitlab cicd jobs could fetch it to create changelogs with a predefined standard formatting.
Ticket: QA-763

chore(ci): centralize git cliff configuration

---

commitlint/commitlint

This is the syntax that GitHub recognizes. See:
* https://docs.github.com/en/pull-requests/committing-changes-to-your-project/creating-and-editing-commits/creating-a-commit-with-multiple-authors
(We want to move away from this tool ASAP, but I have an ever more ASAP pull request to merge that got hit by this)

fix: Accept Co-author footer in our commits

---

.gitlab-ci-check-helm-version-bump.yml

The Helm Version Bump is accepting multiple keys to update the tags.
Ticket: QA-760
* Add support for monorepo (from single `CONTAINER`  to multiple `CONTAINERS` input)
* Add DRY_RUN feature
* not changing the `repository` key: the one in the `values-[staging|prod].yaml` will apply

ci: monorepo support for helm version bump

---

utils/cliff.toml
utils/cliff.toml.scoped

When a commit is scoped, the body is showed, but at the end of the section. Also, adding a newline before the body, for better readability
Ticket: None

fix: commit body didn't show up on scoped commits

---

utils/cliff.toml
utils/cliff.toml.scoped

The No changelog found message is displayed even with new commits, caused by a typo
Ticket: None

ci: fix no changelog found

---

mender-ci-common.sh

This is noisy and can flood the CI logs.

ci: Add quiet flag to upload/download S3 artifacts

---

check_license.sh
license_test.go

This lets us see which files have the wrongly computed checksum, it prints:
* `shasum: WARNING: 1 computed checksum did NOT match` 
`path/to/license/LICENSE: FAILED`
instead of just :
* `shasum: WARNING: 1 computed checksum did NOT match`

chore: don't redirect shasum command to null in check_license.sh 

---

.gitlab-ci-check-docker-build.yml

To avoid runc run failed: unable to start container process: error during container init: error mounting "proc" to rootfs at "/proc" issue
Ticket: QA-823

ci: pin buildkit v0.17

---

.gitlab-ci-check-golang-lint.yml

We need a newer golang version for https://github.com/mendersoftware/integration-test-runner/pull/339

ci: Bump image versions of image used for static checks

---

.gitlab-ci-check-golang-unittests-v2.yml
.gitlab-ci-check-golang-unittests.yml

We need a newer golang version in the unit tests, because go now allows patch-versions for the go version in the go.mod - which some newer dependencies require.

chore: bump golang version

---

.gitlab-ci-check-golang-unittests.yml

We can't get libssl1.1 from the upstream Debian after updating the image.

chore: bump mongodb in golang unit tests

---

.gitlab-ci-check-license.yml

Added env variable override to allow reusing consistent versioning.

ci: Update golang image for running license check

---

.gitlab-ci-check-license.yml

Using default in variable expansion is not allowed for `image` keyword.

ci: Add fallback variable for GOLANG_VERSION

---

.gitlab-ci-check-license.yml

The debian golang image already has git(1) installed.

ci: Remove apk(1) call in check-license call

---

commitlint.config.js
templates/commit-lint.yml

The template uses `commitlint` to lint every commit that is unique to the current branch. The Git logic is a bit cumbersome, but due to our GitHub<->GitLab sync we don't have info on the base branch for the branch being tested.

QA-1032: Add CI/CD component commit-lint

---

templates/brew-build.yml

Otherwise it can make the CI job stuck and doomed to time out (in 1 hour). On top of that, timed-out jobs don't seem to run `after_script` so temporary directories can be left in place.
Ticket: MEN-8331

fix: Prevent brew builds from waiting for input

---

utils/cliff.toml
utils/cliff.toml.scoped

See:
https://github.com/mendersoftware/mender-server-enterprise/pull/546

chore: Switched to sentence case in changelog headings

---

.gitlab-ci-check-docker-deploy.yml

- upgrades the now very EOL `debian:buster` image used in gitlabci to `debian:bookworm`

chore: upgrade debian image used in ci to bookworm

---

templates/workstation-tools-repository.yml

Originally i wanted it to be a template which you extended, but that didn't work due to possible override of `before_script`. I instead made it an anchor, but to use that in files that include the component you can't do the regular `*add_workstation_tools_repository` so you need to use `!reference` https://docs.gitlab.com/ci/yaml/yaml_optimization/#reference-tags 
To use this you must include the component and then you could either do:
```
- !reference [.install_mender_artifact]`
```
or 
```  
- !reference [.add_workstation_tools_repository]
- apt-get install -y mender-artifact
```

feat: component to add workstation-tools-repository

---

templates/release-oslicenses-golang.yml

Otherwise on actual tags (protected refs) the job is not added because there are no changes to the default branch

ci: Fix rules order for adding `release:golanglicenses:generate` CI job

---

templates/release-oslicenses-golang.yml

Instead of relying on the user of the CI/CD component defining an explicit variable. Using the pre-defined one is more robust and follows other templates.

ci: Compare changes against branch using predefined variable
