mendersoftware/mendertesting

licenses.go
=> Remove leftover debug code.

.travis.yml, README.md
Change to codecov, add badges.
=> Build system setup.

check_signed_off.sh
=> Fix non-master branches not being available to signoff test on Travis.

check_license_go_code.sh
=> Make failure in license check more prominent.

check_commits.sh
=> tests: disable pager when listing git commits

check_commits.sh
=> Make sure correct revisions are checked in Gitlab builds.

check_commits.sh
=> Fix commit range detection for Gitlab builds yet again.

.gitlab-ci-check-apidocs.yml
=> Install swagger-cli via npm install -g @apidevtools/swagger-cli

.gitlab-ci-check-docker-build.yml
Proposition to pass the git commit to the build
* goes with https://github.com/mendersoftware/useradm-enterprise/pull/43
ChangeLog:title
=> Pass git commit hash to the docker build

.gitlab-ci-check-docker-build.yml
Description of the build arg
* follow up from https://github.com/mendersoftware/mendertesting/pull/48
ChangeLog:title
=> Updating documentation on COMMIT_TAG build arg

.gitlab-ci-check-docker-acceptance.yml
The existing link is valid, but old.
=> Fix outdated link to mender-artifact.

.gitlab-ci-github-status-updates.yml, .gitlab-ci.yml
=> QA-183: Provide pipeline template for Github status updates.

.gitlab-ci-check-docker-build.yml
=> [docker-build-template] Fix indentation

.gitlab-ci.yml, gitlab_ci_lint.py
So that we prevent breaking the repos using these templates.
=> [pipeline] Add GitLab CI linting for yml files here

.gitlab-ci-check-docker-build.yml
New job to run on <repo>/staging branch. It will trigger saas sync job
once per container in in the repo.
=> [docker-build-template] QA-179: Trigger saas sync on staging changes

.gitlab-ci-check-python3-format.yml
=> [python-formatting-pipeline] skip unnecessary python installation

.gitlab-ci-check-python3-format.yml
=> [python-formatting-pipeline] added missing dependencies after switch to python image

.gitlab-ci-check-docker-build.yml
=> Fix: log in before pulling the image

.gitlab-ci-check-apidocs.yml
=> MEN-3662: Rebuild mender-api-docs on changes of the API spec files

check_license.sh, license_test.go
Previously, a misformed line, like a line with a sha that was missing a
character would pass the check, as the program would only produce a warning, and
not an error code.
This fix makes the program fail on such formatting errors.
Note that it does the verification on a temp-file, as the input license file
needs to be stripped of newlines, as these are also reported as formatting errors.
Example input:
```
8514c577c1c4b46cee454d5a882b15fa411e72c5bd7f801f241591789fce61a  vendor/github.com/spf13/pflag/LICENSE
f6918bd93ffe07f4b2c61b8287c32cb3122e08aed0be50f1c7d0eddc87877a8f  vendor/gopkg.in/ini.v1/LICENSE
5e3400b93bbb099e83e52bab885e7441750673c21f97988ca3f1240639b63283  vendor/github.com/spf13/afero/LICENSE.txt
b40930bbcf80744c86c46a12bc9da056641d722716c378f5659b9e555ef833e1 …
```
=> fix: Make the 'check_license.sh' script fail on format errors

.gitlab-ci-check-docker-acceptance.yml, .gitlab-ci-check-golang-unittests.yml
Reverts mendersoftware/mendertesting#98
=> Revert "QA-220: Migrate coverage reporting to coveralls"

.gitlab-ci-check-golang-unittests.yml
=> Fix typo in gitlab-ci-check-golang-unittests.yml

.gitlab-ci-check-golang-unittests.yml
=> Fix installation of the mongodb-org package in unittests pipeline

.gitlab-ci-check-docker-acceptance.yml
=> QA-221: Remove codecov integration from acceptance template

.gitlab-ci-check-golang-static.yml
=> Fix: gocyclo refactoring and switch to go mod

.gitlab-ci-check-golang-static.yml
=> Restore GO111MODULE=off

.gitlab-ci-check-commits-signoffs.yml, .gitlab-ci-check-commits.yml, .gitlab-ci-check-golang-static.yml, .gitlab-ci-check-license.yml, .gitlab-ci-check-python3-format.yml
Multi stage jobs are not touched since the exact effects have not been
analyzed, and the benefit is not expected to be very significant.
=> Enable immediate execution using "needs: []" for all simple jobs.

.gitlab-ci-check-license.yml
=> Set GIT_DEPTH to 0 in gitlab-ci-check-license.yml

.gitlab-ci-check-license.yml
=> Add documentation for KNOWN_LICENSE_FILES in gitlab-ci-check-license.yml

.gitlab-ci-check-golang-static.yml
Resubmit of #122, rebased on latest master.
=> Fix "go fmt" not being run on packages.

.gitlab-ci-check-golang-unittests.yml
=> Report unit tests' results using go-junit-report

.gitlab-ci.yml, gitlab_ci_lint.py
And add an error message showing the problem
=> QA-274: Disable GitLab CI linting for now

check_license_source_files.sh
=> check_license: Use latest modified year of any commit, not last commit.

.gitlab-ci-check-python3-format.yml
=> Remove extra new line

.gitlab-ci-check-docker-acceptance.yml
=> Support checking out older integration repo for acceptance tests.

.gitlab-ci-check-apidocs.yml, .gitlab-ci-check-docker-build.yml
=> QA-284: Install release_tool requirements from requirements.txt

.gitlab-ci-check-docker-acceptance.yml, .gitlab-ci-check-docker-build.yml
=> Adding double quotes around docker login credentials.

check_commits.sh
=> Fix incorrect skip semantics after loop was moved to function.

.gitlab-ci-check-golang-lint.yml
This adds a check to catch unwanted changes to the monitor directory.
=> [RFC]: MEN-5241: Catch golang dependency modifications

.gitlab-ci-check-golang-lint.yml
=> test:govendor-check: Amend yaml syntax for variables

.gitlab-ci-check-golang-lint.yml
=> Fix exit code for govendor-check.

.gitlab-ci-check-golang-lint.yml, .gitlab-ci-check-golang-static.yml
* Add the template to the static check as well
* Run the check on all branches, not dicounting released, hosted and staging branches.
=> MEN-5241: Follow ups

LICENSE, LIC_FILES_CHKSUM.sha256, check_python_code_format, license_test.go
=> style: Only output the files which need formatting

check_commits.sh
=> fix(buildmaster): Making grammar link clickable

.gitlab-ci-check-commits-signoffs.yml, .gitlab-ci-check-commits.yml
=> fix: do not check commits on saas tags

.gitlab-ci-check-commits.yml
=> ci(commitlint): Add gawk to the commit lint job

.gitlab-ci-check-docker-acceptance.yml, .gitlab-ci-check-golang-lint.yml, .gitlab-ci-check-golang-static.yml, .gitlab-ci-check-golang-unittests.yml, .gitlab-ci.yml
=> chore: upgrade go version to 1.17 for tests, static checks and linting

.gitlab-ci-check-golang-unittests.yml, .gitlab-ci.yml
=> ci: newer go versions have the 'install' command for tools

commitlint/commitlint, commitlint/testcommitlint.sh
=> fix(commitlint): missing sign-off-line token type in the lexer

.gitlab-ci-check-commits.yml
=> fix(commit-check): Do not run the commit check on release tags

LIC_FILES_CHKSUM.sha256
chore(checksums): Change spew library checksum to the correct value
Signed-off-by: Maciej Tomczuk <maciej.tomczuk@northern.tech>
=> chore(checksums): Change spew library checksum to the correct value

commitlint/commitlint, commitlint/testcommitlint.sh
=> fix(commitlint): no space allowed between : and title in the header

.gitlab-ci-check-docker-build.yml
=> ci: made backend image builds use buildkit

commitlint/commitlint
=> fix: Handle weird characters in the Changelog

.gitlab-ci-check-golang-unittests.yml
Missing from commit e4772bacb1cd06e849fd358c89a2c09d2ff21c9b.
=> chore: Add coveralls rerun trigger also in unit tests template

.gitlab-ci-check-docker-build.yml
=> ci: Support customizing the filename path for image load and save

.clang-format, .gitlab-ci-check-c++.yml
Ticket: MEN-6032
Changelog: Title
=> feat: Add code style checking for C/C++.

.gitlab-ci-check-docker-release-indep.yml
Amends commit 630089ee42519237d967093744134cbfbae6ab78
=> fix: Add missing git dependency

.gitlab-ci-check-apidocs.yml, .gitlab-ci-check-c++.yml, .gitlab-ci-check-commits-signoffs.yml, .gitlab-ci-check-commits.yml, .gitlab-ci-check-docker-acceptance.yml, .gitlab-ci-check-docker-build.yml, .gitlab-ci-check-docker-deploy.yml, .gitlab-ci-check-docker-release-indep.yml, .gitlab-ci-check-golang-lint.yml, .gitlab-ci-check-golang-static.yml, .gitlab-ci-check-golang-unittests.yml, .gitlab-ci-check-license.yml, .gitlab-ci-check-python3-format.yml, .gitlab-ci-check-shell-format.yml, .gitlab-ci-github-status-updates.yml, .gitlab-ci.yml
By using existing tag `mender-qa-worker-generic-light`.
=> QA-527: feat: Move all workloads to GCP

.gitlab-ci-check-docker-deploy.yml
=> QA-550: fix: Fix bash script for `sync:image`

commitlint/testcommitlint.sh
=> chore: update bug tracker link

.gitlab-ci-check-apidocs.yml
=> fix: fixed an issue that prevented swagger-cli from running through npx

.gitlab-ci-check-docker-build.yml
Ticket: ALV-27
Added missing `$PUBLISH_IMAGE_DIGEST` env var
=> Fix for publishing multiplatform images

.gitlab-ci-check-docker-build.yml
=> fix: publishing the image SHA to multiplatform builds

.gitlab-ci-check-apidocs.yml
=> chore: API docs spectral lint: print to screen.

.gitlab-ci-check-docker-build.yml
Ticket: QA-613
Changelog: Added multiplatform mender-publishing job
=> Multiplatform mender-publishing

.gitlab-ci-check-docker-build.yml
=> chore: moving the gitlab registry tag to a overridable variable

.gitlab-ci-check-docker-build.yml
Alternative to: https://github.com/mendersoftware/mendertesting/pull/282
=> Adding publishing saas images from staging tags

.gitlab-ci-check-helm-version-bump.yml
=> Move to helm gitrepository with long living branches

.gitlab-ci-check-license.yml
https://github.com/mendersoftware/useradm/pull/381 has a more detailed example
=> chore: made license checking more finegrained to allow using go license checker

.gitlab-ci-check-license.yml, go_licenses_format.tpl
with the default template (Project URL, License URL, detected License), any update to a dependency requires an adjustment to the license file (making it harder than before), thus reducing it to just the project URL + detected license this will not be necessary and only license changes will need adjustments...
once this is merged I'll follow up with PRs to all the repos that have the csv file already
=> chore: adjusted versioned folder preventing automation

.gitlab-ci.yml
=> fix: set `GIT_DEPTH` to 0 to avoid unit test failures when checking licenses

.gitlab-ci-check-commits-signoffs.yml, .gitlab-ci-check-commits.yml, .gitlab-ci-check-license.yml, .gitlab-ci-check-python3-format.yml, .gitlab-ci-check-shell-format.yml, .gitlab-ci-github-status-updates.yml, .gitlab-ci.yml
Ticket: QA-705
Using gitlab.com as a proxy:
```
Pulling docker image gitlab.com:443/northern.tech/dependency_proxy/containers/alpine ...
```
=> using Depencency proxy to save docker pull requests

.gitlab-ci-check-helm-version-bump.yml
=> ci: workaround remote already exists

.gitlab-ci-check-helm-version-bump.yml
=> Using unique local branch name

.gitlab-ci-check-docker-build.yml
To workaround docker rate limit issue
Ticket: QA-730
=> Using gitlab dependency proxy

utils/cliff.toml.scoped
The cliff.toml.scoped is grouping the release notes by groups, and then by scope.
Ticket: QA-773
=> ci: added git cliff scoped conf file

utils/cliff.toml, utils/cliff.toml.scoped
to ensure commit context is present for scoped commits too
=> chore: reduced duplicate commit body render directives 

utils/cliff.toml, utils/cliff.toml.scoped
should address warning from [here](https://gitlab.com/Northern.tech/northerntechhq/nt-gui/-/jobs/8189415809#L409)
=> chore: moved cliff commit parsing to newer github reference

utils/cliff.toml, utils/cliff.toml.scoped
=> chore: create changelog even if empty

.gitlab-ci-check-c++.yml
To speed up submodules, just use the depth:1 and the normal strategy
Ticket: None
=> perf: optimize submodule clone

utils/cliff.toml, utils/cliff.toml.scoped
This should help with further automating releases with Jira `fixedVesrsions`. It won't help external users as they won't be able to access the tickets but it is the same for other projects which are there already (QA, SEC).
=> Add tickets from ME repository to be visible in the changelog.

templates/device-components-repository.yml
This workflow template with make install packages from device-components repo easier and more unified.
Ticket: None
=> feat: Add device-components repository workflow template

.gitlab-ci-check-golang-unittests.yml
=> ci: allow coveralls job to fail
